version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: biblioteca_db
    environment:
      MYSQL_DATABASE: probiblioteca
      MYSQL_ROOT_PASSWORD: eseqele
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: biblioteca_app
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      # Asegúrate de que tu código lea la URL apuntando al servicio 'db' si usa Docker
      - DB_HOST=db

volumes:
  mysql_data: