# Comentarios
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://biblioteca_db:3306/probiblioteca
db.user=root
db.pass=eseqele


# Configuración del pool
hikari.maximumPoolSize=15
hikari.minimumIdle=2
hikari.connectionTimeout=10000
hikari.idleTimeout=300000
hikari.maxLifetime=600000

